name: Build and Release

on:
  push:
    tags:
      - 'v*' 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04 # compatibility issues may occur in the last version, use old version maybe fix.
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name=forward_bot main/__main__.py

      - name: Create tar.gz package
        run: |
          tar -czvf forward_bot.tar.gz -C dist forward_bot -C .. .env

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./forward_bot.tar.gz
          asset_name: forward_bot.tar.gz
          asset_content_type: application/gzip